USE [BANDONGHO]
GO

/****** Object:  Table [dbo].[SANPHAM]    Script Date: 4/23/2024 2:42:23 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SANPHAM](
	[MASP] [int] IDENTITY(1,1) NOT NULL,
	[TENSP] [nvarchar](50) NULL,
	[HINHLON] [varchar](50) NULL,
	[HINHNHO] [varchar](50) NULL,
	[MOTA] [ntext] NULL,
	[MATH] [int] NULL,
	[DANHGIA] [ntext] NULL,
	[SOLUONG] [int] NULL,
	[MALOAISP] [char](7) NULL,
	[DONGIA] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[MASP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_SP_LSP] FOREIGN KEY([MALOAISP])
REFERENCES [dbo].[LOAISANPHAM] ([MALOAISP])
GO

ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_SP_LSP]
GO

ALTER TABLE [dbo].[SANPHAM]  WITH CHECK ADD  CONSTRAINT [FK_SP_TH] FOREIGN KEY([MATH])
REFERENCES [dbo].[THUONGHIEU] ([MATH])
GO

ALTER TABLE [dbo].[SANPHAM] CHECK CONSTRAINT [FK_SP_TH]
GO

